### ISSUE TITLE
utils - apiUrl

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#108]
Hvernig eru þið að setja
`const apiUrl = "";`
Myndi halda að það þyrfti að nota environment variable. til dæmis 
`const apiUrl = process.env.url;`

docker-compose.yml myndi þá vera svona
```
my_game_client:
    image: eythoro16/gameclient:test
    environment:
      url: ${TERRAFOM_IP}
```
og svo bara `export TERRAFORM_IP=$(terraform output public_ip)` í deploy project-inu

er ekki búinn að testa þetta. er að pæla hvort ég sé að of hugsa þetta svona.
hvernig eru þið að gera þetta

**Comment by eythoro16** [comment]
okay. þegar ég runna bara game-client með yarn start þá sé ég vefsíðuna á localhost:4000
En þegar ég runna þetta með docker þá finn ég hvergi vefsíðuna. Hvað er slóðinn fyrir vefsíðuna þegar docker er í gangi?

**Comment by kthorri** [comment]
Getur verið að þú eigir eftir að taka fram portin í docker-compose?

**Comment by eythoro16** [comment]
```
version: '3'
services:
  my_game_api:
    image: eythoro16/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'my_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'my_password'
  my_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'my_password'
  my_game_client:
    image: eythoro16/gameclient:test
    environment:
      PORT: 4000
      GAME_API_URL: ${TERRAFORM_IP}
      GAME_API_PORT: 3000
  my_datadog_container:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=aed6e4161fd28c5811497e5b5b3e0bff
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
```
