### ISSUE TITLE
Cannot curl

### ISSUE THREAD

**Issue by devalberg** [hgop/syllabus-2018#53]
In docker-compose.yml I have set
```
environment:
  PORT: 3000
```
But it still seems like port 3000 is closed even when I try to simply ping it. These are the settings on AWS console that was automated by terraform. I have checked everything in server.js like it should be.

![screenshot from 2018-12-07 12-39-57](https://user-images.githubusercontent.com/26262489/49649336-c4a75c00-fa20-11e8-8f3d-7c93283ba2fd.png)

**Comment by IronPeak** [comment]
What does the game-api output?

**Comment by devalberg** [comment]
Not sure what you mean by game-api output, if it is the log of the public_ip then here it is.

```bash
Outputs:
 
public_ip = 52.203.61.173[0m
+ terraform output public_ip
+ echo Game API running at  + 52.203.61.173
Game API running at  + 52.203.61.173
+ terraform output public_ip
+ ssh -o StrictHostKeyChecking=no -i ~/.aws/GameKeyPair.pem ubuntu@52.203.61.173 ./initialize_game_api_instance.sh
Warning: Permanently added '52.203.61.173' (ECDSA) to the list of known hosts.
```

Full deployment log: https://pastebin.com/BNq2cLU5

**Comment by IronPeak** [comment]
try ssh-ing into the instance and running docker-compose up see what it outputs.
also make sure your API can run locally, to make sure the code is correct.

**Comment by devalberg** [comment]
This is what I get when I do docker-compose up:
```bash
WARNING: The GIT_COMMIT variable is not set. Defaulting to a blank string.
ERROR: no such image: danielev22/hgop:: invalid reference format
```
Even though everything passed through Jenkins and came to SUCCESS at the end

**Comment by devalberg** [comment]
Actually, just figured that I did not change dockerfile to copy everything from game-api... :smile:

**Comment by eythoro16** [comment]
er að lenda í sama.
Dockerfile
```
# Defining base image to use, to start the build process
FROM node:dubnium

# Set the working directory to /code
WORKDIR /code

# copies all the nessisery files to working directory
COPY package.json package.json
COPY database.js database.js
COPY config.js config.js
COPY app.js app.js
COPY context.js context.js
COPY server.js server.js
COPY lucky21.js lucky21.js
COPY deck.js deck.js
COPY dealer.js dealer.js
COPY random.js random.js


# executes "npm install" command.
RUN npm install --production

# default command to be executed
CMD node app.js
```

**Comment by eythoro16** [comment]
```
version: '3'
services:
  my_item_repository:
    image: eythoro16/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_postgres_container
    environment:
      POSTGRES_DB: 'my_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'
      PORT: 3000
  my_postgres_container:
    image: postgres
    environment:
      POSTGRES_DB: 'my_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'
      
```
á þetta ekki að vera svona?
